### ISSUE TITLE
Wikipedia Feeds not displaying images + wrong formatting

### ISSUE THREAD

**Issue by Humorist2601** [msasikanth/twine#395]
**Describe the bug**
Hello, love the app and use it everyday but following three feeds do not display images in them as well as not formatted properly as in does not display any text
The feeds in question are 

- [Wikipedia - Picture of the Day](https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=potd&feedformat=atom)
- [Wikipedia - Featured Article](https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom)
- [Wikipedia - On This Day](https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom)

**To Reproduce**
1. Go to Adding a New feed
2. Add any or all of the above feeds
3. Wait for article to appear

**Screenshots**
![Screenshot_20240321-084107](https://github.com/msasikanth/twine/assets/97790626/02baa9af-c2bc-4198-a14a-089f517adbfb)
![Screenshot_20240321-084126](https://github.com/msasikanth/twine/assets/97790626/97e04fb4-e85e-4cd8-a303-18268bb45483)
![Screenshot_20240321-084136](https://github.com/msasikanth/twine/assets/97790626/17b36156-a091-49d0-8904-c3f0734ec391)

**Device Information**
 - Device: Pixel 4a 5g
 - OS: Android 14
 - App Version [e.g. 1.0.0]

**Comment by Humorist2601** [comment]
Opened this issue on March 21 but due to my account being flagged it just became visible.

**Comment by msasikanth** [comment]
Thanks for reporting the issue. Apart from the images, did the formatting issue resolved in the newer versions of the app?

**Comment by Humorist2601** [comment]
- The "On This Day" Feed sometimes doesn't display anything after a line or so
![Screenshot_20240428-110059](https://github.com/msasikanth/twine/assets/97790626/99f1eae2-d215-4830-9c3c-b4e749af8c92)

- The "Feature Article" Feed has been working fine but the image issue remains

- "Picture of the Day" still shows the wrong formatting with all text alinged to the very right as displayed with the image in the original post

This all was tested with the latest nightly
